# Generated by Django 3.1.6 on 2021-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediamodel',
            name='instagram',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Email Address (Company)'),
        ),
    ]
