# Generated by Django 3.1.6 on 2021-02-13 19:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_title_text', models.CharField(default=' ', max_length=100, verbose_name='Header Title')),
                ('header_text', models.CharField(default=' ', max_length=200, verbose_name='Header Text')),
                ('our_story_title', models.CharField(default=' ', max_length=100, verbose_name='Our Story Title')),
                ('our_story_richtext', wagtail.core.fields.RichTextField(blank=True, max_length=1000, verbose_name='Our Story')),
                ('first_member_of_team_twitter', models.URLField(blank=True, null=True, unique=True, verbose_name='Twitter web page')),
                ('first_member_of_team_facebook', models.URLField(blank=True, null=True, unique=True, verbose_name='Facebook web page')),
                ('first_member_of_team_instagram', models.URLField(blank=True, null=True, unique=True, verbose_name='Instagram web page')),
                ('first_member_of_team_linkedin', models.URLField(blank=True, null=True, unique=True, verbose_name='Linedin web page')),
                ('first_member_of_team_name', models.CharField(default=' ', max_length=30, verbose_name='Full Name')),
                ('first_member_of_team_position', models.CharField(default=' ', max_length=30, verbose_name='Organizational Position')),
                ('first_member_of_team_description', models.CharField(default=' ', max_length=100, verbose_name='Description')),
                ('second_member_of_team_twitter', models.URLField(blank=True, null=True, unique=True, verbose_name='Twitter web page')),
                ('second_member_of_team_facebook', models.URLField(blank=True, null=True, unique=True, verbose_name='Facebook web page')),
                ('second_member_of_team_instagram', models.URLField(blank=True, null=True, unique=True, verbose_name='Instagram web page')),
                ('second_member_of_team_linkedin', models.URLField(blank=True, null=True, unique=True, verbose_name='Linedin web page')),
                ('second_member_of_team_name', models.CharField(default=' ', max_length=30, verbose_name='Full Name')),
                ('second_member_of_team_position', models.CharField(default=' ', max_length=30, verbose_name='Organizational Position')),
                ('second_member_of_team_description', models.CharField(default=' ', max_length=100, verbose_name='Description')),
                ('third_member_of_team_twitter', models.URLField(blank=True, null=True, unique=True, verbose_name='Twitter web page')),
                ('third_member_of_team_facebook', models.URLField(blank=True, null=True, unique=True, verbose_name='Facebook web page')),
                ('third_member_of_team_instagram', models.URLField(blank=True, null=True, unique=True, verbose_name='Instagram web page')),
                ('third_member_of_team_linkedin', models.URLField(blank=True, null=True, unique=True, verbose_name='Linedin web page')),
                ('third_member_of_team_name', models.CharField(default=' ', max_length=30, verbose_name='Full Name')),
                ('third_member_of_team_position', models.CharField(default=' ', max_length=30, verbose_name='Organizational Position')),
                ('third_member_of_team_description', models.CharField(default=' ', max_length=100, verbose_name='Description')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated_time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='pub_time')),
                ('banner_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('first_member_of_team_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('our_story_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('second_member_of_team_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('third_member_of_team_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
