# Generated by Django 3.1.6 on 2021-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='first_member_of_team_instagram',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='second_member_of_team_instagram',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='third_member_of_team_instagram',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
