# Generated by Django 3.1.6 on 2021-03-21 13:02

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210315_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='our_story_img',
            new_name='about_us_img',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='our_story_richtext',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='our_story_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_left_richtext',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=500, verbose_name='About Us Left Paragraph'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_right_richtext',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=500, verbose_name='About Us Right Paragraph'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_title',
            field=models.CharField(default=' ', max_length=100, verbose_name='About Title'),
        ),
    ]
