# Generated by Django 3.1.6 on 2021-03-15 14:22

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='products_text',
            field=wagtail.core.fields.RichTextField(default=' ', max_length=1000, verbose_name='Products Text'),
        ),
    ]
